#%RAML 1.0 NamedExample
value: [
  {
    "accountId": "1357902468",
    "accountType": "SAVINGS",
    "displayName": "Savings Account",
    "description": "Check Transfer",
    "accountStatus": "OPEN",
    "accountDescriptorId": 111,
    "customerId": "111111101",
    "transactionId": "111222333444555",
    "transactionTimestamp": "2018-07-12",
    "status": "PENDING",
    "amount": 1000
   
  },
  {
    "accountId": "1357902468",
    "accountType": "SAVINGS",
    "displayName": "Savings Account",
    "description": "Check Transfer",
    "accountStatus": "OPEN",
    "accountDescriptorId": 111,
    "customerId": "111111101",
    "transactionId": "111222333444555",
    "transactionTimestamp": "2018-07-12",
    "status": "PENDING",
    "amount": 1000
   
  }
]